#!/usr/bin/env ruby

require_relative '../lib/rage_flip'

# Get the arguments passed to the script
args = ARGV

# Flip the arguments
flipped_args = RageFlip.flip(args)

# Copy the result to the clipboard based on the platform
case RUBY_PLATFORM
when /darwin/
  IO.popen('pbcopy', 'w') { |f| f << flipped_args }
when /linux/
  IO.popen('xclip -selection clipboard', 'w') { |f| f << flipped_args }
when /mingw|mswin/
  require 'win32ole'
  clipboard = Win32::OLE.new('HTMLFile')
  clipboard.ParentWindow.ClipboardData.SetData('text', flipped_args)
else
  puts "Unsupported platform. Please copy the output manually."
end

puts "Flipped arguments copied to clipboard: #{flipped_args}"